# Generated by Django 6.0.5 on 2026-07-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('idade', models.CharField(max_length=3)),
                ('personagem', models.CharField(max_length=150)),
                ('local_de_nascimento', models.CharField(max_length=150)),
                ('imagem', models.ImageField(upload_to='elenco/')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('autor', models.CharField(max_length=150)),
                ('ano_de_lancamento', models.CharField(max_length=4)),
                ('resumo', models.TextField()),
                ('capa', models.ImageField(upload_to='capa/')),
                ('elenco', models.ManyToManyField(to='app.ator')),
            ],
        ),
    ]
